#!/usr/bin/env node
/**
 * Every link in `llms.txt` resolves to a page the site actually serves — REQ-048 (#207), task #217, AC-6.
 *
 * `llms.txt` is documentation for a reader that cannot click. A person following a broken link sees a 404 and
 * tries something else; an agent following one cites it, or concludes the page does not exist and answers from
 * whatever it already believed. That is the failure this file exists for, and it was real: the generator linked
 * `docs/02-core-and-persistence.md` as `/02-core-and-persistence` while the site serves it at
 * `/specifications/core-and-persistence`. Every specification link in the index was a 404, and nothing noticed,
 * because nothing had ever followed one.
 *
 * Runs after the site build in `ci:local`, because the built output is the only honest answer to "does this URL
 * exist" — the alternative is re-deriving Docusaurus's routing here and being wrong in a different way.
 *
 * Exit codes: 0 clean, 1 a link that resolves to nothing, 2 the check could not run.
 */

import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const INDEX = "website/static/llms.txt";
const BUILD = "website/build";

/** Site-internal links only. An external URL is somebody else's to keep alive. */
export const internalLinks = (markdown) =>
  [...markdown.matchAll(/\]\((\/[^)\s]*)\)/g)].map((match) => match[1]);

/**
 * Whether the built output serves this path.
 *
 * A Docusaurus route is a directory with an `index.html`, so both forms are accepted; a `.html` sibling is
 * accepted too, since a future config change could emit that instead and failing on it would be this check
 * enforcing an implementation detail rather than the guarantee.
 */
export const served = (build, path) => {
  const clean = path.replace(/[?#].*$/, "").replace(/\/$/, "");
  if (clean === "") return existsSync(join(build, "index.html"));
  return (
    existsSync(join(build, clean, "index.html")) ||
    existsSync(join(build, `${clean}.html`)) ||
    existsSync(join(build, clean))
  );
};

const main = () => {
  let markdown;
  try {
    markdown = readFileSync(INDEX, "utf8");
  } catch (error) {
    console.error(`✗ cannot read ${INDEX}: ${error.message}`);
    console.error("  it is generated by website/scripts/gen-llms.mjs during the site's prebuild");
    return 2;
  }
  if (!existsSync(BUILD)) {
    console.error(`✗ ${BUILD} does not exist, so no link could be checked`);
    console.error("  build the site first: npm --prefix website run build");
    return 2;
  }

  const links = internalLinks(markdown);
  if (links.length < 20) {
    console.error(`✗ ${INDEX} yielded only ${links.length} internal link(s) — the index changed shape`);
    return 2;
  }

  const broken = links.filter((link) => !served(BUILD, link));
  if (broken.length > 0) {
    console.error(`✗ ${broken.length} of ${links.length} links in ${INDEX} resolve to nothing:`);
    for (const link of broken.slice(0, 12)) console.error(`  · ${link}`);
    console.error("  an agent following one cites a 404, or decides the page does not exist and answers from");
    console.error("  memory instead — which is worse than having no index at all");
    return 1;
  }

  console.log(`✓ all ${links.length} links in ${INDEX} are served by ${BUILD}`);
  return 0;
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main());
