import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Auto-generate the sidebar from the docs/ folder. Numeric filename prefixes (01-, 02-, …)
// set the order; subfolders (extraction/, api/) become categories.
const sidebars: SidebarsConfig = {
  specs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
