import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Auto-generated API reference (TypeDoc → typedoc-plugin-markdown).
const sidebars: SidebarsConfig = {
  api: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
