import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The internal specifications (design docs), auto-generated from ../docs.
const sidebars: SidebarsConfig = {
  specs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
